# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x04test\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2l\n\x08\x44\x65livery\x12-\n\x04Send\x12\x11.test.TextRequest\x1a\x12.test.TextResponse\x12\x31\n\x04\x43hat\x12\x11.test.TextRequest\x1a\x12.test.TextResponse(\x01\x30\x01\x62\x06proto3'
)




_TEXTREQUEST = _descriptor.Descriptor(
  name='TextRequest',
  full_name='test.TextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='test.TextRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_TEXTRESPONSE = _descriptor.Descriptor(
  name='TextResponse',
  full_name='test.TextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='test.TextResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['TextRequest'] = _TEXTREQUEST
DESCRIPTOR.message_types_by_name['TextResponse'] = _TEXTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRequest = _reflection.GeneratedProtocolMessageType('TextRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TextRequest)
  })
_sym_db.RegisterMessage(TextRequest)

TextResponse = _reflection.GeneratedProtocolMessageType('TextResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.TextResponse)
  })
_sym_db.RegisterMessage(TextResponse)



_DELIVERY = _descriptor.ServiceDescriptor(
  name='Delivery',
  full_name='test.Delivery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='test.Delivery.Send',
    index=0,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_TEXTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='test.Delivery.Chat',
    index=1,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_TEXTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DELIVERY)

DESCRIPTOR.services_by_name['Delivery'] = _DELIVERY

# @@protoc_insertion_point(module_scope)
